
parameters:

    lmh_money.currency_manager.class: Lmh\Bundle\MoneyBundle\Service\CurrencyManager
    lmh_money.currency_code_validator.class: Lmh\Bundle\MoneyBundle\Service\CurrencyCodeValidator
    lmh_money.annotation_reader.class: Lmh\Bundle\MoneyBundle\Service\AnnotationReader
    lmh_money.field_mapper.class: Lmh\Bundle\MoneyBundle\Service\FieldMapper
    lmh_money.field_mapper.currency.class: Lmh\Bundle\MoneyBundle\Mapper\CurrencyMapper
    lmh_money.field_mapper.money.class: Lmh\Bundle\MoneyBundle\Mapper\MoneyMapper

services:

    lmh_money.currency_manager:
        class: "%lmh_money.currency_manager.class%"
        arguments:
            - "%lmh_money.currency_configuration_filename%"
            - "%lmh_money.currencies%"

    validator.unique.currency_code_validator:
        class: "%lmh_money.currency_code_validator.class%"
        arguments: [ @lmh_money.currency_manager ]
        tags:
            - { name: validator.constraint_validator, alias: currency_code_validator }

    lmh_money.field_mapper:
        class: "%lmh_money.field_mapper.class%"
        arguments:
            - @lmh_money.currency_manager
            - @annotation_reader # doctrine annottion reader

    lmh_money.field_mapper.currency:
        class: "%lmh_money.field_mapper.currency.class%"
        arguments: [ @lmh_money.currency_manager ]
        tags:
            - { name: lmh_money.field_mapper, annotation: \Lmh\Bundle\MoneyBundle\Annotation\Currency }
            - { name: lmh_money.field_mapper, annotation: \Lmh\Bundle\MoneyBundle\Annotation\Two }
            - { name: lmh_money.field_mapper, annotation: \Lmh\Bundle\MoneyBundle\Annotation\Three }

    lmh_money.field_mapper.money:
        class: "%lmh_money.field_mapper.money.class%"
        arguments: [ @lmh_money.currency_manager ]
        tags:
            - { name: lmh_money.field_mapper, annotation: \Lmh\Bundle\MoneyBundle\Annotation\Money }
