
parameters:

    matmar10_money.currency_manager.class: Matmar10\Bundle\MoneyBundle\Service\CurrencyManager

    # validators
    matmar10_money.validator.currency.class: Matmar10\Bundle\MoneyBundle\Validator\InstanceValidator
    matmar10_money.validator.currency_code.class: Matmar10\Bundle\MoneyBundle\Validator\CurrencyCodeValidator
    matmar10_money.validator.currency_pair.class: Matmar10\Bundle\MoneyBundle\Validator\InstanceValidator
    matmar10_money.validator.exchange_rate.class: Matmar10\Bundle\MoneyBundle\Validator\InstanceValidator
    matmar10_money.validator.money.class: Matmar10\Bundle\MoneyBundle\Validator\InstanceValidator

    # composite property service
    matmar10_money.composite_property_service.class: Matmar10\Bundle\MoneyBundle\Service\CompositePropertyService

    # strategies
    matmar10_money.composite_property_strategy.currency.class: Matmar10\Bundle\MoneyBundle\PropertyStrategy\Currency
    matmar10_money.composite_property_strategy.currency_pair.class: Matmar10\Bundle\MoneyBundle\PropertyStrategy\CurrencyPair
    matmar10_money.composite_property_strategy.exchange_rate.class: Matmar10\Bundle\MoneyBundle\PropertyStrategy\ExchangeRate
    matmar10_money.composite_property_strategy.money.class: Matmar10\Bundle\MoneyBundle\PropertyStrategy\Money

services:

    ##
    # currency manager
    ##

    matmar10_money.currency_manager:
        class: "%matmar10_money.currency_manager.class%"
        arguments:
            - "%matmar10_money.currency_configuration_filename%"
            - "%matmar10_money.currencies%"

    ##
    # validators
    ##

    matmar10_money.validator.currency_validator:
        class: "%matmar10_money.validator.currency.class%"
        tags:
            - { name: validator.constraint_validator, alias: currency_validator }

    matmar10_money.validator.currency_code_validator:
        class: "%matmar10_money.validator.currency_code.class%"
        arguments: [ @matmar10_money.currency_manager ]
        tags:
            - { name: validator.constraint_validator, alias: currency_code_validator }

    matmar10_money.validator.currency_pair_validator:
        class: "%matmar10_money.validator.currency_pair.class%"
        tags:
            - { name: validator.constraint_validator, alias: currency_pair_validator }

    matmar10_money.validator.exchange_rate_validator:
        class: "%matmar10_money.validator.exchange_rate.class%"
        tags:
            - { name: validator.constraint_validator, alias: exchange_rate_validator }

    matmar10_money.validator.money_validator:
        class: "%matmar10_money.validator.money.class%"
        tags:
            - { name: validator.constraint_validator, alias: money_validator }

    ##
    # composite property service
    ##

    matmar10_money.composite_property_service:
        class: "%matmar10_money.composite_property_service.class%"
        arguments:
            - @matmar10_money.currency_manager
            - @annotation_reader # doctrine annotation reader

    ##
    # composite property strategies
    ##

    matmar10_money.composite_property_strategy.currency:
        class: "%matmar10_money.composite_property_strategy.currency.class%"
        arguments: [ @matmar10_money.currency_manager ]
        tags:
            - { name: composite_property_strategy, annotation: \Matmar10\Bundle\MoneyBundle\Annotation\Currency }

    matmar10_money.composite_property_strategy.currency_pair:
        class: "%matmar10_money.field_mapper.currency_pair.class%"
        arguments: [ @matmar10_money.currency_manager ]
        tags:
            - { name: composite_property_strategy, annotation: \Matmar10\Bundle\MoneyBundle\Annotation\CurrencyPair }

    matmar10_money.composite_property_strategy.exchange_rate:
        class: "%matmar10_money.field_mapper.exchange_rate.class%"
        arguments: [ @matmar10_money.currency_manager ]
        tags:
            - { name: composite_property_strategy, annotation: \Matmar10\Bundle\MoneyBundle\Annotation\ExchangeRate }

    matmar10_money.field_mapper.money:
        class: "%matmar10_money.field_mapper.money.class%"
        arguments: [ @matmar10_money.currency_manager ]
        tags:
            - { name: composite_property_strategy, annotation: \Matmar10\Bundle\MoneyBundle\Annotation\Money }
